### ISSUE TITLE
Failed to fetch study (id=1)

### ISSUE THREAD

**Issue by LucaMarconato** [optuna/optuna-dashboard#137]
### Description

Everything works fine, then at a certain point I start getting this error message when trying to look at one study, and from that moment that study would load anymore (while I will still be able to see other studies).

This is just a problem of the dashboard, because from Python I will still be able to load and look at studies, and also to train more models on them.

I am using the SQLite backend.

I am not sure what causes the bug, but while I was running an hyperparameters optimization for two studies at a certain point I have noticed the error messages shown on the screenshot on the console of the optimization process of one of the two studies. From around that moment I started getting the above error message in that study (while the other study remained accessible).
Notices that the memntioned error message don't affect the training of the model or the optimization process. Also after a few epochs it disappeared.

Extra details: once I got a similar error message also when loading the homepage. I had to create a new .sqlite study. Not sure if the problem is related to the one above.

<img width="1290" alt="Screen Shot" src="https://user-images.githubusercontent.com/2664412/133695329-46e00f5a-5a3f-4c8e-a775-cd76f790fdd7.png">

### How to Reproduce

1. Optuna's objective function is 'validation_elbo' (a float to minimize).
2. Run optuna-dashboard with 'optuna-dashboard sqlite:///optuna.sqlite --port 8798'
3. go to the optuna dashboard homepage, then click on the name of a study to enter
4. everything works fine, then at a certain point the error message above will appear (see above for discussion); from that moment the study will be not accessible from the dashboard (while other studies will remain accessible)

### Python version

3.8.5

### Optuna version

2.9.1

### optuna-dashboard version or git revision

0.4.2

### Web browser

Google Chrome, Firefox and Safari

**Comment by LucaMarconato** [comment]
I have just experienced the issue for a study in which I did not get the error regarding `multiprocessing` shown in the screenshot above. So I don't know why, but after a while virtually all my studies become unexplorable from the dashboard.

**Comment by c-bata** [comment]
By using optuna-dashboard while the optimization, multiple workers (the process of Optuna and the process of optuna-dashboard) tried to connect SQLite3. Actually the locking system of SQLite3 is not perfect. It may raise DatabaseLockError. This is the reason why Optuna also does not recommend using SQLite3 for parallel optimization.

> We do not recommend SQLite for distributed optimizations at scale because it may cause deadlocks and serious performance issues. Please consider to use another database engine like PostgreSQL or MySQL.
> https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html

Please use MySQL or PostgreSQL to avoid this error.
