### ISSUE TITLE
 ModuleNotFoundError: No module named 'MySQLdb'

### ISSUE THREAD

**Issue by Jie-Yuan** [optuna/optuna-dashboard#140]
# PLEASE USE GITHUB DISCUSSIONS

Don’t use GitHub Issues to ask support questions. Use the [GitHub Discussions](https://github.com/optuna/optuna-dashboard/discussions/categories/q-a) for that.

**Comment by c-bata** [comment]
Please install PyMySQL or mysqliclient.
https://docs.sqlalchemy.org/en/14/dialects/mysql.html#dialect-mysql
