### ISSUE TITLE
Responsive width large screens

### ISSUE THREAD

**Issue by thedimlebowski** [optuna/optuna-dashboard#142]
# Responsive width

On wide screens, the content doesn't scale responsively. It makes it harder to decipher plots.
![image](https://user-images.githubusercontent.com/6419212/134339345-98c00e88-634a-4b30-88c3-aa126d17a384.png)

**Comment by ezioishan** [comment]
I would love to work on this issue if its not already been taken

**Comment by ezioishan** [comment]
@c-bata I have submitted a PR regarding the issue, please let me know if the issue still exists. Thanks :)
