### ISSUE TITLE
Can we add comment on the dashboard website

### ISSUE THREAD

**Issue by ZedRover** [optuna/optuna-dashboard#155]
# Feature Request

I believe that it's more convient for us if we can add comment on the front-end website of dashboard.Otherwise, sometimes we can only watch the dashboard and can't write down our ideas

**Comment by sayantan1410** [comment]
I would like to contribute to it !! Can you please give me some information about how to get started to work on this enhancement ?

**Comment by c-bata** [comment]
Please read [Developers Guide](https://github.com/optuna/optuna-dashboard/blob/main/DEVELOPMENT.md), then you can implement this feature in following steps.

1. Add a new API endpoint to save comment messages in `study.system_attrs`.
1. Add textarea and button tags at the bottom of the study detail page.
1. Add a checkbox to enable/disable this feature in [the preference panel](https://github.com/chenghuzi/optuna-dashboard/blob/370ee0ca57a71e72bd11558859c437955ce10cc0/optuna_dashboard/static/components/StudyDetail.tsx#L178-L273).

**Comment by sayantan1410** [comment]
Sorry for the delay, I will surely read the Guide and will ask if I am stuck at somewhere. 
Thank you and Merry Christmas :)
