### ISSUE TITLE
Do not reload graphs when zoomed in

### ISSUE THREAD

**Issue by t-moe** [optuna/optuna-dashboard#17]
Currently, when I zoom into a graph (e.g. intermediate values), the graph is reset as soon as the network fetch in the background completes (every 10s?).

It would be nice if:
* there was a button to stop autoreload
* or the graph interactions would be restored/kept across data reloads

Otherwise, I love it! Thank you so much for the project

**Comment by c-bata** [comment]
Thank you for reporting!
I implemented switch button to disable auto-reloading at #18 but I can't make up my mind where we should put this button.
If you have an idea, please comment to the pull request.
