### ISSUE TITLE
Study Status 

### ISSUE THREAD

**Issue by guangmingjian** [optuna/optuna-dashboard#202]
# Feature Request

*Please write your suggestion here.*
Many studies may be running at the same time. If the running status of the study can be added on the home page, we don't need to enter the study to check whether the study is completed. Thanks!

**Comment by keisuke-umezawa** [comment]
In the Optuna specification, there is no "completed" state for a Study, and you can always add trials later to resume experiments. Therefore, adding this feature is difficult within the specification.
