### ISSUE TITLE
Api call returns always cached data [Bug]

### ISSUE THREAD

**Issue by p-sodmann** [optuna/optuna-dashboard#23]
# Bug reports
The api call to http://localhost:8080/api/studies/1 always returns the result from the first call since it gets cached and the cache is never invalidated.

## Expected Behavior

Invalidate the cache every 10 seconds and return new values.

## Current Behavior and Steps to Reproduce

Currently the dashboard will not update after initialization.

## Context

Please provide any relevant information about your setup.
This is important in case the issue is not reproducible except for under certain conditions.

Optuna version 2.4
* `optuna-dashboard --version`: 0.2.1

**Comment by c-bata** [comment]
Thank you for reporting this critical issue. I fixed this at #24. I will release v0.2.2 after merged the pull request.

**Comment by c-bata** [comment]
I've just published v0.2.2 at PyPI. Thank you, again!
https://github.com/optuna/optuna-dashboard/releases/tag/v0.2.2
https://pypi.org/project/optuna-dashboard/

**Comment by p-sodmann** [comment]
It does work now as intended, thank you for the fast solution!
