### ISSUE TITLE
Wrong container image tag: "latast"

### ISSUE THREAD

**Issue by rsnitsch** [optuna/optuna-dashboard#231]
### Description

There is a typo in your container tagging logic. Instead of "latest" you're adding the tag "latast". For this reason, the "latest" tag has not been updated for 2 months: https://github.com/optuna/optuna-dashboard/pkgs/container/optuna-dashboard/versions

So if someone is referring to the repo as `ghcr.io/optuna/optuna-dashboard` he is currently not getting the latest version as expected.

Please fix the typo.

### How to Reproduce

n/a

### Python version

n/a

### Optuna version

n/a

### optuna-dashboard version or git revision

n/a

### Web browser

n/a

**Comment by c-bata** [comment]
Oh, thank you. I'll fix this soon :bow:
