### ISSUE TITLE
Intermediate values plot: Lines go in circles

### ISSUE THREAD

**Issue by rsnitsch** [optuna/optuna-dashboard#232]
### Description

My intermediate values plot is broken. The lines go in circles. See screenshot:

![image](https://user-images.githubusercontent.com/1746428/167442827-bea4a92a-e5c5-48a5-a341-4da43e13dc36.png)

### How to Reproduce

At first I thought it could be related to using earlystop, but the minimal example I devised did not reproduce the issue.

Now I suspect it is because I run my trials in parallel, distributed across many workers. But I haven't tested this yet.

### Python version

3.9

### Optuna version

2.10.0

### optuna-dashboard version or git revision

0.6.4

### Web browser

Microsoft Edge

**Comment by rsnitsch** [comment]
I have now created some example code that reproduces this issue:
https://github.com/rsnitsch/optuna-dashboard-intermediate-values-plot-issue-232

**Comment by c-bata** [comment]
Thank you for reporting the bug and creating reproducible code! I'll check it later.
