### ISSUE TITLE
Default display for parallel coordinates should be grey scale

### ISSUE THREAD

**Issue by blazespinnaker** [optuna/optuna-dashboard#262]
# Feature Request

When you have a lot of trials, the parallel coordinates is not informative at all because the it's just one blob, however the grey scale image is very informative.

eg:
![Screenshot 2022-08-14 9 36 04 AM](https://user-images.githubusercontent.com/2188809/184546417-db23b169-afe7-40b4-9c96-98963ffb6042.png)

compared to

![Screenshot 2022-08-14 9 38 42 AM](https://user-images.githubusercontent.com/2188809/184546439-86f4f7c2-e8f5-42e5-9bda-17cbdd3b6172.png)

Also, it's not immediately obvious that you can select and highlight the vertical bars, which is very useful.

**Comment by keisuke-umezawa** [comment]
@blazespinnaker Thank you for registering this issue!
This issue will be resolved by https://github.com/optuna/optuna-dashboard/pull/280, although we will not use gray scale, but blue scale because Optuna uses this color scale.

**Comment by c-bata** [comment]
Thanks @keisuke-umezawa and @blazespinnaker !
Let me close this issue since #280 is merged.
