### ISSUE TITLE
Change the default behaviour to not create new databases.

### ISSUE THREAD

**Issue by leo-hstone** [optuna/optuna-dashboard#263]
# Feature Request

Thanks for optuna, it is an awesome tool! What had cost me a few minutes recently was, that optuna-dashboard automatically creates new storages. I had a typo in the url, which led to the creation but the website did not show anything. It took me a while, as I was not expecting to be able to create storages with optuna-dashboard.

In my understanding, optuna-dashboard is just a display tool (with minimalistic ways of interaction) and should warn the user if it creates a new storage, or even return an error. With a simple command line switch, one could toggle that behaviour.

**Comment by c-bata** [comment]
Thank you for your report! I've just opened #320 to fix this bug.
