### ISSUE TITLE
[Feature] Support plot_slice to show the parameter relationship.

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna-dashboard#28]
# Feature Request

Porting `plot_slice()` to TypeScript.
https://github.com/optuna/optuna/blob/v2.4.0/optuna/visualization/_slice.py

**Comment by 2403hwaseer** [comment]
Hey @c-bata , this sounds interesting to me. I want to contribute to this. Can you please help me figure out the "how-to" part?

**Comment by c-bata** [comment]
Sounds good! The source code of React.js application is here:
https://github.com/optuna/optuna-dashboard/tree/main/optuna_dashboard/static

Please read them and add a new React.js component for this features.

**Comment by 2403hwaseer** [comment]
Okay! I'll have a look.

**Comment by 2403hwaseer** [comment]
Hey @c-bata , I was trying to understand the code of `_slice.py` . Now that I have got an idea, I'll start making the React component.
However, I had a doubt. I made a minor change in the header of `StudyDetail.tsx` component and obseved that the change was not being reflected on the dashboard. Can you please help me figure out why?

I changed the way we display AppBar title
from ``<Typography variant="h6">{APP_BAR_TITLE}</Typography>`` 
to ``<Typography variant="h1">{APP_BAR_TITLE}</Typography>``

**Comment by c-bata** [comment]
I'm not sure but you can see the changes if javascript files were built successfully. Steps to build javascript are written at DEVELOPMENT.md.
https://github.com/optuna/optuna-dashboard/blob/main/DEVELOPMENT.md

Furthermore, it looks that you change the `variant` property. It might not to see the changes unless you inspect the DOM via developer console.

**Comment by 2403hwaseer** [comment]
Hey @c-bata , thanks for the link to the documentation. I figured out the error, there was some issue with environment variables. I think I solved it, I'll start working on it!
