### ISSUE TITLE
add constraints checkbox

### ISSUE THREAD

**Issue by okaikov** [optuna/optuna-dashboard#316]
# Feature Request

Hello,
I would appreciate if you can add the constraints functionality, and add a checkbox for choosing only trials that meet the constraints.
this functionality already exists in optuna.visualization.plot_pareto_front().
need to add this to: history & pareto front.

You can check the system attributes to see if it meets the constraints.

**Comment by c-bata** [comment]
Sounds good! Thank you for your suggestion 👍

**Comment by ldesmet** [comment]
Hello @okaikov @c-bata , my 2cents on this topic

1/ I don't think there is a checkbox in optuna.visualization.plot_pareto_front, only an argument to consider if trials satisfy constraints or not, but it plots all trials yet.

2/ This should be a new feature directly added to optuna right ? Like if we specify constraints in the sampler, it should consider these constraints in the pareto front directly ?

Have a great day,

**Comment by okaikov** [comment]
AFAIK the actual constarints are stored at trial.SYSTEM_ATTR, no?

**Comment by hrntsm** [comment]
Hi @okaikov 
I've implemented this in #525, please check it out!

**Comment by c-bata** [comment]
@hrntsm Thank you for your pull request. Let me close this issue.

@okaikov Please feel free to reopen this issue if you have additional suggestions or feedbacks.
