### ISSUE TITLE
Remove eslint warnings

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna-dashboard#32]
There are some warnings of eslint.

* [x] StudyList.tsx
* [x] StudyDetail.tsx
* [ ] GraphParallelCoordinate.tsx
* [ ] GraphHistory.tsx
* [ ] DataGrid.tsx
* [ ] apiClient.ts
* [ ] action.ts

**Comment by hegdeashwin** [comment]
Recently, I started exploring optuna with regards to my internal company project and I'm willing to contribute this feature with guidance from the optuna community.

**Comment by hegdeashwin** [comment]
@c-bata I guess you must be busy, but just wanted to know any update on review for the raised PR [https://github.com/optuna/optuna-dashboard/pull/93](https://github.com/optuna/optuna-dashboard/pull/93)
