### ISSUE TITLE
Support for JournalStorage

### ISSUE THREAD

**Issue by matteo-bastico** [optuna/optuna-dashboard#379]
# Feature Request

Hello, 

In Optuna 3.1.0, `JournalFileStorage`, a file storage backend based on `JournalStorage`,  has been introduced to allow distributed optimization in environments where it is not possible to setup a database server.  

Nevertheless, this kind of storage is not compatible yet with the Optuna Dashboard, according to [its implementation](https://github.com/optuna/optuna-dashboard/blob/81451c6fd42507dda00bb9255506d8a040453273/optuna_dashboard/_app.py#L405-L415). It might be interesting to provide support for this storage or to provide a workaround to convert the study from journal storage to an RDB storage. 

Thank you!

**Comment by c-bata** [comment]
@matteo-bastico Thank you for the suggestion. It sounds worth considering!

For now, you can use `JournalStorage` via the following Python API provided by optuna-dashboard.

```python
# main.py
from optuna_dashboard import run_server

storage = JournalStorage(JournalFileStorage("./optuna.log"))
run_server(storage, host="127.0.0.1", port: int = 8080)
```

```
$ python main.py
```

Also you can use the third party WSGI servers (e.g. Gunicorn, uWSGI, etc.) via `optuna_dashboard.wsgi()` function.

```python
# main.py
from optuna_dashboard import app

storage = JournalStorage(JournalFileStorage("./optuna.log"))
app = wsgi(storage)
```

```
$ pip install gunicorn
$ gunicorn --workers 4 main:app
```
