### ISSUE TITLE
TypeError: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.

### ISSUE THREAD

**Issue by threeq** [optuna/optuna-dashboard#400]
### Description

![image](https://user-images.githubusercontent.com/4645905/219610985-d5007f42-eebc-400c-80a7-e4197c218cf5.png)

### How to Reproduce

1. Optuna's objective function is 

```
    def objective(trial):
        param = Dict(
                period_signal_diff=2,
                period_trend=trial.suggest_categorical('period_trend', [60, 120]),
                period_signal=trial.suggest_categorical('period_signal', [5, 10, 20]),
                position_risk=trial.suggest_categorical('position_risk', [0.005, 0.01, 0.02]),
                hold_max_days=trial.suggest_int('hold_max_days', 30, 32, 2),
                max_pos_num=trial.suggest_int('max_pos_num', 10, 10, 1),
            )
        return runner(param)
```

3. Run optuna-dashboard with 'Edge'
4. Open 'http://127.0.0.1:8080/dashboard/studies/1/analytics' page
5. An error occurs.

### Python version

Python 3.7.0

### Optuna version

3.1.0

### optuna-dashboard version or git revision

0.9.0b6

### Web browser

Edge

**Comment by almostintuitive** [comment]
@threeq : I'm bumping into the same issue, how did you end up resolving it? thank you for your help!

**Comment by c-bata** [comment]
@almostintuitive Could you open a new issue?
