### ISSUE TITLE
Optuna Dashboard not loading a study and returning a blank white screen.

### ISSUE THREAD

**Issue by DeepankurK** [optuna/optuna-dashboard#401]
### Description

I ran a study with 20 variables for 100 trials with one objective. My study is sequential and runs for a 6 hrs approx. Therefore I use "study.tell()" to update the study in an asynchronous manner. 

I encountered this issue when loading my study in optuna dashboard. Even with one trial complete, the dashboard for the study does not load and just shows a blank screen.

I ran some tests with dummy objective functions to test if optuna-dashboard does not work with study updates in the manner I am feeding to the study and I found that the dashboard does not load. While using the same objective function and calling study.optimize() do result in plotting of the dashboard.

Sample Code : 

```python
def objective(trial):
  a = trial.suggest_float("a", -100, 100)
  b = trial.suggest_categorical("b", [-1, 0, 1])
  c = trial.suggest_float("c", -100, 100)
  d = trial.suggest_categorical("d", [-1, 0, 1])
  e = trial.suggest_float("e", -100, 100)
  f = trial.suggest_categorical("f", [-1, 0, 1])
  g = trial.suggest_float("g", -100, 100)
  h = trial.suggest_categorical("h", [-1, 0, 1])
  
  return a+b+c+d+e+f+g+h

if __name__ == "__main__":
  study = optuna.create_study(
        storage="sqlite:///db.sqlite3",  # Specify the storage URL here.
        study_name="test"
        )
  trial=study.ask()
  to_tell=objective(trial)
  study.tell(trial,to_tell)
  print(f"Best value: {study.best_value} (params: {study.best_params})")
```

### How to Reproduce

I am attaching a sample trial of the original study:

FrozenTrial(number=0, values=[-1976.0], datetime_start=datetime.datetime(2023, 2, 17, 17, 56, 4, 338326), datetime_complete=datetime.datetime(2023, 2, 17, 17, 58, 43, 593847), params={'Alpha': 0.4, 'BestLevelTopStay': -1, 'BetaCloseBest': 0.0, 'BetaCloseCancel': 0.05, 'BetaCloseCross': 0.15000000000000002, 'BetaCloseImprove': 0.0, 'BetaOpen': 0.0, 'CanStageExposure': 0, 'Cancel': -0.2, 'CloseMultiplier': 1.0, 'Continuous': 0, 'Cross': 1.4, 'CrossBufferQty': 0, 'CrossSpreadMult': 0.01, 'CrossableThreshold': -1, 'DefaultQtyInLot': 50, 'DeltaCancelBestImprove': 0.0, 'Duration': 0, 'ExtMaxPos': -1, 'ExtremeMktAllowed': 0, 'ExtremelyHigh': -1, 'Improve': 0.2, 'ImproveSpreadMult': 0.01, 'IsAssumeFillEnabled': 0, 'IsCryptoImprove': 1, 'IsDeepImprove': 1, 'IsPreemptiveImprove': 1, 'MarketMaking': 0, 'MarketMakingQty': 0, 'MaxAllowedSpreadForImprove': 200, 'MaxImproveEntry': 0, 'MaxImproveExit': 125, 'MaxPosInLot': 400, 'MaxSpreadForStableMkt': -1, 'MaxSpreadToCrossEntry': 100, 'MaxSpreadToCrossExit': 125, 'MaxSpreadToCrossSecondLevel': 300, 'MinAllowedSpreadForBest': 1, 'MinQtyAllowedForBest': -1, 'PosMult': 0.0, 'PosMultExit': 0.0, 'PositionAdjustment': 4, 'QtyDefiningOneLevel': 0, 'Replace': 0, 'SignalDeepImp': 0.01, 'SignalPreemptiveImp': 0.01, 'SmallQuantity': 0, 'SpreadMult': 0.01, 'StratBestLevel': 1, 'StratCross': 90, 'StratDeepLevel': 1, 'StratImprove': 1, 'StrongSideQty': 110, 'TickVariablesInBP_10': 0, 'WeakSideQty': 10}, distributions={'Alpha': FloatDistribution(high=0.7, log=False, low=0.3, step=0.1), 'BestLevelTopStay': IntDistribution(high=-1, log=False, low=-1, step=1), 'BetaCloseBest': FloatDistribution(high=0.2, log=False, low=0.0, step=0.05), 'BetaCloseCancel': FloatDistribution(high=0.2, log=False, low=0.0, step=0.05), 'BetaCloseCross': FloatDistribution(high=0.2, log=False, low=0.0, step=0.05), 'BetaCloseImprove': FloatDistribution(high=0.2, log=False, low=0.0, step=0.05), 'BetaOpen': FloatDistribution(high=0.0, log=False, low=0.0, step=1.0), 'CanStageExposure': IntDistribution(high=0, log=False, low=0, step=1), 'Cancel': FloatDistribution(high=0.0, log=False, low=-0.4, step=0.1), 'CloseMultiplier': FloatDistribution(high=1.0, log=False, low=1.0, step=1.0), 'Continuous': IntDistribution(high=0, log=False, low=0, step=1), 'Cross': FloatDistribution(high=1.4, log=False, low=0.6, step=0.2), 'CrossBufferQty': IntDistribution(high=0, log=False, low=0, step=1), 'CrossSpreadMult': FloatDistribution(high=0.01, log=False, low=0.01, step=1.0), 'CrossableThreshold': IntDistribution(high=-1, log=False, low=-1, step=1), 'DefaultQtyInLot': IntDistribution(high=50, log=False, low=50, step=1), 'DeltaCancelBestImprove': FloatDistribution(high=0.0, log=False, low=0.0, step=1.0), 'Duration': IntDistribution(high=0, log=False, low=0, step=1), 'ExtMaxPos': IntDistribution(high=-1, log=False, low=-1, step=1), 'ExtremeMktAllowed': IntDistribution(high=0, log=False, low=0, step=1), 'ExtremelyHigh': IntDistribution(high=-1, log=False, low=-1, step=1), 'Improve': FloatDistribution(high=0.2, log=False, low=0.0, step=0.05), 'ImproveSpreadMult': FloatDistribution(high=0.01, log=False, low=0.01, step=1.0), 'IsAssumeFillEnabled': IntDistribution(high=0, log=False, low=0, step=1), 'IsCryptoImprove': IntDistribution(high=1, log=False, low=1, step=1), 'IsDeepImprove': IntDistribution(high=1, log=False, low=0, step=1), 'IsPreemptiveImprove': IntDistribution(high=1, log=False, low=0, step=1), 'MarketMaking': IntDistribution(high=0, log=False, low=0, step=1), 'MarketMakingQty': IntDistribution(high=0, log=False, low=0, step=1), 'MaxAllowedSpreadForImprove': IntDistribution(high=400, log=False, low=100, step=100), 'MaxImproveEntry': IntDistribution(high=100, log=False, low=0, step=25), 'MaxImproveExit': IntDistribution(high=200, log=False, low=100, step=25), 'MaxPosInLot': IntDistribution(high=400, log=False, low=400, step=1), 'MaxSpreadForStableMkt': IntDistribution(high=-1, log=False, low=-1, step=1), 'MaxSpreadToCrossEntry': IntDistribution(high=200, log=False, low=100, step=25), 'MaxSpreadToCrossExit': IntDistribution(high=150, log=False, low=50, step=25), 'MaxSpreadToCrossSecondLevel': IntDistribution(high=300, log=False, low=300, step=1), 'MinAllowedSpreadForBest': IntDistribution(high=1, log=False, low=1, step=1), 'MinQtyAllowedForBest': IntDistribution(high=-1, log=False, low=-1, step=1), 'PosMult': FloatDistribution(high=0.0, log=False, low=0.0, step=1.0), 'PosMultExit': FloatDistribution(high=0.0, log=False, low=0.0, step=1.0), 'PositionAdjustment': IntDistribution(high=4, log=False, low=4, step=1), 'QtyDefiningOneLevel': IntDistribution(high=0, log=False, low=0, step=1), 'Replace': IntDistribution(high=0, log=False, low=0, step=1), 'SignalDeepImp': FloatDistribution(high=0.01, log=False, low=0.01, step=1.0), 'SignalPreemptiveImp': FloatDistribution(high=0.01, log=False, low=0.01, step=1.0), 'SmallQuantity': IntDistribution(high=0, log=False, low=0, step=1), 'SpreadMult': FloatDistribution(high=0.01, log=False, low=0.01, step=1.0), 'StratBestLevel': IntDistribution(high=3, log=False, low=0, step=1), 'StratCross': IntDistribution(high=90, log=False, low=10, step=20), 'StratDeepLevel': IntDistribution(high=3, log=False, low=1, step=1), 'StratImprove': IntDistribution(high=3, log=False, low=1, step=1), 'StrongSideQty': IntDistribution(high=110, log=False, low=50, step=20), 'TickVariablesInBP_10': IntDistribution(high=0, log=False, low=0, step=1), 'WeakSideQty': IntDistribution(high=90, log=False, low=10, step=20)}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=301, state=TrialState.COMPLETE, value=None)
Trial  0  matched.

### Python version

3.7.16

### Optuna version

3.1.0

### optuna-dashboard version or git revision

0.8.1

### Web browser

Firefox

**Comment by c-bata** [comment]
@DeepankurK Huge thanks for reporting this bug!
I've opened #402 to fix this bug and will be released in v0.9.0b7 release.
