### ISSUE TITLE
Specifying names for multi objective optimization

### ISSUE THREAD

**Issue by ldesmet** [optuna/optuna-dashboard#404]
# Feature Request

Hello everyone and thanks for you great work. 
I think it would be nice if we could specify the name of the objectives in case of multi objectives

![image](https://user-images.githubusercontent.com/85343730/220948776-fd8e7195-8b20-4518-8f57-64d7b0a09d32.png)

What do you think ?

Thanks,

**Comment by c-bata** [comment]
@idesmet Could you try using `set_objective_names(study, ["objective 1", "objective 2"])` with optuna-dashboard v0.9.0b6?

```
$ pip install optuna-dashboard>=0.9.0b6
```

```python
import optuna
from optuna_dashboard import set_objective_names

def objective(trial):
    ...

study = optuna.create_study(..., directions=["minimize", "maximize"])
set_objective_names(study, ["objective 1", "objective 2"])
study.optimize(objective, ...)
```

https://github.com/optuna/optuna-dashboard/discussions/332#discussioncomment-5075800

**Comment by ldesmet** [comment]
Hello @c-bata and thanks for your answer. This did not solved the issue. Behavior is still the same. Version of optuna is 3.1.0

**Comment by ldesmet** [comment]
Hello ! Downgrading optuna to 3.0.0 fixed the issue. Thanks again !

**Comment by c-bata** [comment]
Perhaps, you need to forget hard reloading. Please file a bug report if it does not work with Optuna 3.1.0.
