### ISSUE TITLE
Different plots outputs on dashboard and by using optuna.visualization modules

### ISSUE THREAD

**Issue by guscaldas** [optuna/optuna-dashboard#422]
### Description

As the title says, I observed that different output plots are given depending when accessing on the brownser (by executing optuna-dashboard command with Optuna storage URL) or when running one of the commands from optuna.visualization modules. 

For instance, when running optuna.visualization.plot_optimization_history(study), the history plot is different from the one given in the dashboard. Same for optuna.visualization.plot_param_importances(study), in which even the values are different.

My guess: it seems that on the dashboard, both finished and pruned trials are shown, while in the optuna.visualization modules, only finished trials are shown. I would like to see both finished and pruned trials on the visualization modules. 

Another case, but for an uncomplete trial, I can access the figures in the dashboard (see attached), while running in the command, I get: 
$ optuna.visualization.plot_optimization_history(study)
"[W 2023-03-29 22:19:48,717] There are no complete trials."
$ optuna.visualization.plot_param_importances(study)
"[W 2023-03-29 22:26:35,927] Study instance does not contain completed trials."
![newplot (2)](https://user-images.githubusercontent.com/45698163/228703964-6888221d-58ab-4903-8513-4d12a345c7d0.png)
![newplot (3)](https://user-images.githubusercontent.com/45698163/228704195-42be2c4f-1ddf-429b-bb16-915cf24a7512.png)

### How to Reproduce

1. For running the dashboard
optuna-dashboard sqlite:///db.sqlite3

2. For running the optuna.visualization modules
import plotly.io as pio
pio.renderers.default='browser'

optuna.visualization.plot_intermediate_values(study)
optuna.visualization.plot_param_importances(study)

### Python version

3.9.16

### Optuna version

3.1.0

### optuna-dashboard version or git revision

0.8.1

### Web browser

Google Chrome

**Comment by c-bata** [comment]
Thank you for using optuna-dashboard!

As for the importance values, it depends on the seed value. So I think it's not a bug. As for the history plot, your guess is almost correct. optuna-dashboard shows both finished and pruned trials by default. You can also show only completed trials by unchecking the "PRUNED" button like below.

![Screenshot 2023-03-30 10 53 11](https://user-images.githubusercontent.com/5564044/228707744-b57f9f94-b545-41f5-90d7-e31bad47c231.png)

**Comment by guscaldas** [comment]
> Thank you for using optuna-dashboard!
> 
> As for the importance values, it depends on the seed value. So I think it's not a bug. As for the history plot, your guess is almost correct. optuna-dashboard shows both finished and pruned trials by default. You can also show only completed trials by unchecking the "PRUNED" button like below.
> 
> ![Screenshot 2023-03-30 10 53 11](https://user-images.githubusercontent.com/5564044/228707744-b57f9f94-b545-41f5-90d7-e31bad47c231.png)

Thanks for your fast response. 
Can I have both finished and pruned trials shown on the visualization module?
When I run the parallel coordinates command, the result is also different: on the dashboard it is more "dense", with more lines. That's why I guess that the visualization modules show only complete trials. 
(Sorry I cannot share my figures because I will publish them)

**Comment by c-bata** [comment]
@guscaldas Currently, Optuna's visualization module does not support to show pruned trials.
https://github.com/optuna/optuna/blob/master/optuna/visualization/_optimization_history.py#L51

Could you please create a new issue on the Optuna repository? The design seems to be controversial and may not be straightforward though.
https://github.com/optuna/optuna/issues/new?assignees=&labels=feature&template=feature-request.yml
