### ISSUE TITLE
Crash when opening a study from SQLite DB

### ISSUE THREAD

**Issue by oiao** [optuna/optuna-dashboard#430]
### Description

When running `optuna-dashbopard` on an sqlite database, the app crashes when a specific study is opened.
The following error is reported in the browser:
``` js
bundle.js:2 TypeError: Cannot read properties of undefined (reading 'toFixed')
    at bundle.js:75:87217
    at Array.map (<anonymous>)
    at Gd (bundle.js:75:87184)
    at bundle.js:75:85809
    at zl (bundle.js:2:3854012)
    at e.unstable_runWithPriority (bundle.js:2:3879817)
    at qi (bundle.js:2:3794696)
    at Il (bundle.js:2:3853475)
    at bundle.js:2:3853386
    at D (bundle.js:2:3878877)
```

### How to Reproduce

1. Optuna's objective function is likely irrelevant here?
2. Run optuna-dashboard with `optuna-dashboard sqlite:///db.sqlite3 --port 4422`
3. Open `http://127.0.0.1:4422/dashboard/studies/1`
4. An error occurs.

### Python version

3.10.10

### Optuna version

3.1.1

### optuna-dashboard version or git revision

0.9.0

### Web browser

Chrome

**Comment by c-bata** [comment]
Thank you for your report!
Perhaps the error is related to https://github.com/optuna/optuna-dashboard/issues/410. Could you share the minimal reproducible code?

**Comment by oiao** [comment]
Thanks a lot for the reply. Opening the same DB after a night of trials seems to have solved the problem - not sure what the issue was there. Will close for now and re-open if it appears again. Sorry for the trouble.
