### ISSUE TITLE
Add multiple storage databases

### ISSUE THREAD

**Issue by Kevin-wangyu** [optuna/optuna-dashboard#447]
# Feature Request

There seems to be a huge blank space on the home page for displaying multiple storage databases, is it possible that use the function "run_server(storage_urls)" to achive it?

**Comment by c-bata** [comment]
Thank you for using optuna-dashboard!

Sorry, I couldn't understand what  "multiple storage database" means. Is this the similar feature request with https://github.com/optuna/optuna-dashboard/issues/398?
