### ISSUE TITLE
Follow up the implementation of the screen to compare the multiple studies

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna-dashboard#466]
By https://github.com/optuna/optuna-dashboard/pull/380, we implemented the screen to compare the multiple studies. But, we still have some issues to be fixed. I will make a list of issues here.

# Issues to be fixed

*Please write your suggestion here.*
- [x] Need to merge the implementation of GraphHistoryMultiStudies and GraphHistory ref: https://github.com/optuna/optuna-dashboard/pull/380#issuecomment-1483999028
- [x] Need to merge the implementation of GraphEdfMultiStudies and GraphEdf ref: https://github.com/optuna/optuna-dashboard/pull/380#issuecomment-1483999028
- [x] To show the number of directions on the trial list
- [x] ~Remove redundant access to DB when viewing study 1 and viewing study 2 will get study 1 again~
    -  It will be solved by adding pagination functionality to optuna.storages.

**Comment by beyarkay** [comment]
WOW THIS IS SO COOL! I just discovered this feature and it's _really_ handy. Literally the only thing I'd recommend is to make it more discoverable (but maybe that's a me problem).

No other comments, just wanted to say that I appreciate the work that's been put into making the new version of the dashboard really nice ❤️ .
