### ISSUE TITLE
add progress bar when loading a study

### ISSUE THREAD

**Issue by okaikov** [optuna/optuna-dashboard#479]
# Feature Request

when loading a large study (thousands of trials), the loading time is significant. I can't tell if the server have crashed,  or if it's still loading the study.
would be nice to have a progress bar to see the status.

**Comment by contramundum53** [comment]
@y0z is working on this problem.

**Comment by contramundum53** [comment]
Just FYI, I could generate a DB that makes both loading study list and trial list slow.

```python
import optuna

data = [123456789 for i in range(1000)]
def objective(trial: optuna.Trial):
    x = trial.suggest_uniform('x', 0, 1)
    trial.set_user_attr("data", data)
    return x

for i in range(100):
    study = optuna.create_study(study_name=f'test-{i}', storage='sqlite:///slow.db', sampler=optuna.samplers.RandomSampler())
    for i in range(1000):
        study.set_user_attr(f"data{i}", data)
    study.optimize(objective, n_trials=1000)
```

Currently no progress bar or "now loading..." shows at all, and users might believe that there are no studies/trials.
