### ISSUE TITLE
Timeline plot doesn't handle many trials

### ISSUE THREAD

**Issue by candyflower2005** [optuna/optuna-dashboard#487]
### Description

Hi,
the timeline trial doesn't correctly show results for >100 trials.

By default, it shows the latest 100 trials. When I scroll to check earlier trials, they don't appear. Zooming out doesn't show them too. Screenshots are attached. Is is a general problem with the timeline plot or maybe I'm doing something wrong?

![image](https://github.com/optuna/optuna-dashboard/assets/48383942/ce0cbc34-49f9-4897-aca6-4a99d0c03df5)
![image](https://github.com/optuna/optuna-dashboard/assets/48383942/734f0961-3433-4113-aeca-3d1a0db37da4)

### How to Reproduce

Produce e.g. 200 trials.

### Python version

3.8

### Optuna version

3.2.0

### optuna-dashboard version or git revision

0.10.0b1

### Web browser

Google Chrome

**Comment by keisuke-umezawa** [comment]
thank you for your feedback.
At the moment, we limited the maximum number to show [here](https://github.com/optuna/optuna-dashboard/blob/main/optuna_dashboard/ts/components/GraphTimeline.tsx#L8).
But, if you want to see more numbers, we will think about some solutions.

**Comment by candyflower2005** [comment]
Thank you! It would be great to have it. I found this plot to be very useful in monitoring the state of prunning.

**Comment by HideakiImamura** [comment]
I would like to get this feature. This is just one idea, but how about allowing the number of trials to be displayed in a pull-down format to be adjusted?

**Comment by HideakiImamura** [comment]
Let me add a contribution-welcome label for this issue.

**Comment by keisuke-umezawa** [comment]
> I would like to get this feature. This is just one idea, but how about allowing the number of trials to be displayed in a pull-down format to be adjusted?

@HideakiImamura 
Let me work on it.

**Comment by candyflower2005** [comment]
Thank you @keisuke-umezawa. That's super helpful!
