### ISSUE TITLE
History plot reverts the "Include PRUNED trials" -setting

### ISSUE THREAD

**Issue by mikael-nyman-km** [optuna/optuna-dashboard#501]
### Description

History plot shows pruned trials when setting slider is off:
![Screenshot from 2023-06-15 10-46-45](https://github.com/optuna/optuna-dashboard/assets/87808418/86b7d0b2-75c4-45ea-b0de-639a163df690)

It hides them when setting is on:
![Screenshot from 2023-06-15 10-46-38](https://github.com/optuna/optuna-dashboard/assets/87808418/64936571-c8eb-46c1-b0dd-9ed2c864265c)

Intermediate values -plot works as expected

### How to Reproduce

1. Run optuna study where some trials will get pruned
2. Open optuna dashboard
3. Toggle "Include PRUNED trials" -slider

### Python version

3.10.6

### Optuna version

3.2.0

### optuna-dashboard version or git revision

0.10.2

### Web browser

Firefox 114.0.1

**Comment by c-bata** [comment]
Good catch! Thank you for your report 🙇
