### ISSUE TITLE
Suggestion: Make value of best trial (and maybe trial count) visible for each study in ://dashboard

### ISSUE THREAD

**Issue by L1nkus** [optuna/optuna-dashboard#511]
# Feature Request

Suggestion: Make value of best trial (and maybe trial count) visible for each study in ://dashboard

Just as direction is visible. As if you have lots of similarly-named past studies, it can help figure out which ones were the bigger or more successful ones

Could also give the user choice whether to show that

**Comment by keisuke-umezawa** [comment]
@L1nkus 
Thank you for reaching out to us!
There is an issue that has been open for a long time, so let's merge this issue into it and discuss this topic there.
https://github.com/optuna/optuna-dashboard/issues/252
