### ISSUE TITLE
dashboard crashed the study with "OperationalError: database is locked"

### ISSUE THREAD

**Issue by FlorinAndrei** [optuna/optuna-dashboard#545]
### Description

I had a study running locally, using SQLite.

```python
def objective(trial, study_name):
    pipe_args = make_pipe_args(trial)
    model_args = make_model_args(trial, study_name)

    pipe_preproc = rebuild_pipe_preproc_from_args(pipe_args=pipe_args)
    pipe = rebuild_model_pipe_from_args(model_name=study_name, pipe_preproc=pipe_preproc, model_args=model_args)

    return test_performance(pipe=pipe, X=X, y=y, n_splits=num_folds, n_jobs=cpu_count)

for m in baseline_models:
    odb_file = 'optuna_' + m + '.db'
    study[m] = optuna.create_study(
        direction='minimize',
        study_name=m,
        storage='sqlite:///' + odb_file,
        load_if_exists=True,
    )

for m in baseline_models:
    study[m].optimize(lambda trial: objective(trial, m), n_trials=3000, catch=(ValueError,), show_progress_bar=False)
```

I launched the dashboard:

```
optuna-dashboard --host 0.0.0.0 sqlite:///optuna_xgboost.db
```

...and then I discovered my study crashed:

```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
File [~/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1133](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e20.vscode-resource.vscode-cdn.net/home/florin/kaggle/feature_engineering/~/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1133), in Connection._commit_impl(self)
   1132 try:
-> 1133     self.engine.dialect.do_commit(self.connection)
   1134 except BaseException as e:

File [~/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py:696](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e20.vscode-resource.vscode-cdn.net/home/florin/kaggle/feature_engineering/~/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py:696), in DefaultDialect.do_commit(self, dbapi_connection)
    695 def do_commit(self, dbapi_connection):
--> 696     dbapi_connection.commit()

OperationalError: database is locked
```

This never happened while using the Optuna CLI.

### How to Reproduce

1. Optuna's objective function is - see above.
2. Run optuna-dashboard with - see above
3. Just explore the dashboard, see what it does.
4. An error occurs.

### Python version

3.11.4

### Optuna version

3.3.0

### optuna-dashboard version or git revision

0.11.0

### Web browser

Google Chrome

**Comment by c-bata** [comment]
As described in [the SQLAlchemy’s documentation](https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#sqlite-concurrency), SQLite3 (and pysqlite driver) does not support a high level of concurrency. You may get a “database is locked” error, which occurs when one thread or process has an exclusive lock on a database connection (in reality a file handle) and another thread times out waiting for the lock to be released.

You can mitigate this issue by increasing the default [timeout](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect) value like `optuna.storages.RDBStorage(“sqlite:///example.db”, engine_kwargs={“connect_args”: {“timeout”: 20.0}})`.
