### ISSUE TITLE
Sorting values in trials table

### ISSUE THREAD

**Issue by Koowah** [optuna/optuna-dashboard#578]
### Description

Hello,

Not a big issue but often, when wanting to sort values in the trials table, I get this type of result.
Any idea why that might be ?

Thanks 😄 

![image](https://github.com/optuna/optuna-dashboard/assets/81920095/052df2c3-8273-47eb-9ba3-5bd65ad0568b)

### How to Reproduce

Get values and try to sort them

### Python version

3.11.4

### Optuna version

3.3.0

### optuna-dashboard version or git revision

0.12.0

### Web browser

Google Chrome

**Comment by c-bata** [comment]
@Koowah Thank you for your report! I opened #580 to fix this bug.
