### ISSUE TITLE
parallel coordinate plot cannot handle small numbers using mantiassa/exponent notation

### ISSUE THREAD

**Issue by pyscorcher** [optuna/optuna-dashboard#61]
# Bug reports

When one coordinate of the parallel coordinate plots gets values that are small enough (that we usually write with the floating point notation as e.g. `1e-10`), the plot will show them in a random order (and not sorted as you would expect form a numerical coordinate):  

Consider following screenshot. The numbers are completely out of order.

![grafik](https://user-images.githubusercontent.com/59569502/120337695-d4ebd980-c2f3-11eb-83e6-68b92a8b7cdf.png)

## Expected Behavior

I expect that the values are sorted in ascending order, and ideally have some nice spacing between the different labelled points.

## Current Behavior and Steps to Reproduce

Currently these values are probably treated as categorical values. I suspect this is because under the hood the values are converted to strings. While numbers that are displayed using the floating point format (containing the `e` to separate mantissa and exponent) fail, numbers that are just written using digits and a decimal separator work fine. 

I used following code to generate the database file:
```
import optuna


def objective(trial: optuna.trial.BaseTrial):
    lr = trial.suggest_loguniform('lr', low=1e-10, high=1e-5)
    loss = lr
    return loss

if __name__ == '__main__':
    study = optuna.create_study(
        study_name='test',
        storage="sqlite:///test.db",
        load_if_exists=True,
        direction='minimize'
        )

    study.optimize(objective, n_trials=10)
    print(f'{study.best_params=}')
```

## Context

* Optuna Version `2.5.0` (ubuntu):
* Optuna-Dashboard version `0.2.2` (win):

**Comment by c-bata** [comment]
This bug seemed to be resolved at https://github.com/optuna/optuna-dashboard/pull/226.
Thank you for the report.
