### ISSUE TITLE
The links of human-in-the-loop optimization utilizing objective form widgets in https://github.com/optuna/optuna-dashboard/blob/main/docs/tutorials/preferential-optimization.rst are broken.

### ISSUE THREAD

**Issue by shu65** [optuna/optuna-dashboard#667]
### Description

The links of ` human-in-the-loop optimization utilizing objective form widgets` in https://github.com/optuna/optuna-dashboard/blob/main/docs/tutorials/preferential-optimization.rst are broken.

### How to Reproduce

1. access https://github.com/optuna/optuna-dashboard/blob/main/docs/tutorials/preferential-optimization.rst
2. Click on the next links

i. It differs from [human-in-the-loop optimization utilizing objective form widgets](https://github.com/optuna/optuna-dashboard/blob/main/docs/tutorials/tutorial-hitl-objective-form-widgets)
ii. aligining with the problem setting in [this tutorial](https://github.com/optuna/optuna-dashboard/blob/main/docs/tutorials/tutorial-hitl-objective-form-widgets).

### Python version

None

### Optuna version

None

### optuna-dashboard version or git revision

None

### Web browser

Google Chrome

**Comment by c-bata** [comment]
I've just opened #671. Thank you for your report 👍
