### ISSUE TITLE
Cannot deselect first trials

### ISSUE THREAD

**Issue by jannessm** [optuna/optuna-dashboard#670]
### Description

When I try to deselect the first trail in the intermediate values plot, I can only click on the plotly buttons. Same applies for the timeline plot.

Maybe a padding of some pixels already fixes this behavior.

![image](https://github.com/optuna/optuna-dashboard/assets/14215334/243ca7f3-0dd5-4fc3-8d88-1e27a2052279)

### How to Reproduce

1. Optuna's objective function is unimportant.
2. Run optuna-dashboard with standard args
3. Open History page, then TRY clicking trail 0.
4. you probably zoom in or out

### Python version

3.9.16

### Optuna version

3.4.0

### optuna-dashboard version or git revision

0.13.0

### Web browser

Google Chrome

**Comment by jannessm** [comment]
Also, When scrolling some trials are not visible:

![image](https://github.com/optuna/optuna-dashboard/assets/14215334/8aecdd08-5264-4b95-a40f-43bab4d654c7)
![image](https://github.com/optuna/optuna-dashboard/assets/14215334/ef5b842e-b06e-4135-99ba-7721ba9cfaa2)

**Comment by KebabRonin** [comment]
This issue is back as of 13 June 2024

### Python version
3.11.0

### Optuna version
3.6.1

### optuna-dashboard version
0.15.1

### Web browser
OperaGX, Edge, Google Chrome

**Comment by DavidCohen2** [comment]
I also have the same problem, and I would appreciate your help.

**Python version**
3.10.14

**Optuna version**
3.6.1

**optuna-dashboard version**
0.15.1

**Web browser**
Google Chrome
