### ISSUE TITLE
Ignore outlier

### ISSUE THREAD

**Issue by R-N** [optuna/optuna-dashboard#673]
# Feature Request

My trial values are mostly around 0-1, but there's this one outlier at 10^20 and it's really annoying that I can't zoom in. Even after zooming in 5x using the zoom tool I'm still at 50T range then somehow it suddenly jumps back to autoscale at 10^20... meaning I can't zoom in.

**Comment by c-bata** [comment]
Thank you for your report.
We understand this situation may be frustrating. However, we currently do not have plans to implement an 'ignore outlier' feature. As for the problem related to the zoom-in resetting, there's a workaround. You can prevent the zoom-in from resetting by clicking on the "Reload" icon on the left side of the screen, which will disable the live updates.
