### ISSUE TITLE
Support buttons to filter trial states

### ISSUE THREAD

**Issue by s-ryosky** [optuna/optuna-dashboard#69]
# Feature Request

Currently, the button for filtering the trial states seems to be reflected only in the main graph,
but I want the filtered states to be reflected in other graphs as well.

**Comment by c-bata** [comment]
Thank you for your suggestion! I apologize that it takes long time, but I've released v0.9.0b2 that supports this suggestion.

<img width="1750" alt="optuna-dashboard" src="https://user-images.githubusercontent.com/5564044/212051395-f61c4084-1601-4e08-907c-1e876c2558e1.png">

https://github.com/optuna/optuna-dashboard/discussions/332
