### ISSUE TITLE
Providing user with the number of completed / failed / pruned/ running trials

### ISSUE THREAD

**Issue by candyflower2005** [optuna/optuna-dashboard#710]
# Feature Request

Hi,
would it be possible to expose the number of trials in each of these categories? Or is it already available? The only way I see is to compute it manually.

Providing such statistics would allow users not only to quickly measure effectiveness or their pruning method, but also to detect if their jobs are less healthy by tracking the ratio of failed and successful trials.

**Comment by nabenabe0928** [comment]
Is it what you want?

![image](https://github.com/optuna/optuna-dashboard/assets/47781922/d092ffc7-1b0d-4598-ad6a-9c8fe0768199)

You can see it in "Trials (List)" -> The filter button at the top left corner of the page.
