### ISSUE TITLE
Study_id is incorrect when using cockroach SQL backend

### ISSUE THREAD

**Issue by pongnguy** [optuna/optuna-dashboard#725]
### Description

When creating a new study, or accessing an existing one, the study_id is different in the dashboard from the database.  Therefore, the webpage gives an error.

### How to Reproduce

1. optuna-dashboard  --port 8083 cockroachdb://root@cockroach_host:26257/defaultdb?sslmode=disable
2. Create a new study or access an existing one.  The study_id on the webpage is different from what is stored in the database.

### Python version

3.10

### Optuna version

3.4.0

### optuna-dashboard version or git revision

0.13.0

### Web browser

Chrome

**Comment by adjeiv** [comment]
Took a look into this, it's an issue with CockroachDB's maximum integer size, which greatly exceeds the maximum size that JavaScript can handle, leading to these unexpected results.

The following article is relevant: https://www.cockroachlabs.com/docs/stable/int#considerations-for-64-bit-signed-integers. A few suggestions are provided there; I'm not sure whether there's too much to be done on optuna's side, aside from perhaps a warning if this backend is being used...

**Comment by pongnguy** [comment]
Thanks @adjeiv for looking into this.  Yes, a warning would be good, pending future updates (if any).
