### ISSUE TITLE
x-ticklabel disappers when we use the light color mode

### ISSUE THREAD

**Issue by nabenabe0928** [optuna/optuna-dashboard#733]
### Description

Here is the dark mode and we can see the x ticklabels:

![image](https://github.com/optuna/optuna-dashboard/assets/47781922/4bd5be90-92e8-4a4a-8862-acc87a9f976a)

However, we cannot see them in the light color mode
![image](https://github.com/optuna/optuna-dashboard/assets/47781922/c24105f4-f935-43b4-9a7a-6b3465aa9c92)

### Python version

3.9

### Optuna version

3.5.0

### optuna-dashboard version or git revision

0.14.0

### Web browser

Google Chrome

**Comment by hrntsm** [comment]
I assume this problem was fixed in v0.15, am I correct?

![Screenshot 2024-03-26 at 18 23 18](https://github.com/optuna/optuna-dashboard/assets/23289252/b818ae63-5d60-43a5-b4a1-e95df746ed16)

**Comment by c-bata** [comment]
I confirmed that this bug was fixed. Thank you for your report.
