### ISSUE TITLE
Please apply `word-break: break-all` to the study name field

### ISSUE THREAD

**Issue by nodakai** [optuna/optuna-dashboard#745]
# Feature Request

Please apply `word-break: break-all` to the study name field

https://github.com/optuna/optuna-dashboard/blob/6b05c98f356b461183a6a70aa2f0ded47e92bc7d/standalone_app/src/components/StudyList.tsx#L170

(if I'm not mistaken, this component is displayed in `/dashboard`, right?)

CSS reference: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

I frequently deal with `Study` objects that have long names, often more than 60 chars, due to encoding a variety of hyper-hyper-parameters. Currently, with the default `word-break`, the display is limited to roughly the first 30 characters in a 500 px width space.

**Comment by c-bata** [comment]
Thank you for your suggestion! I've just merged #835 which addresses this issue.
