### ISSUE TITLE
Add Documentation for `optuna_dashboard.artifact.get_artifact_path`

### ISSUE THREAD

**Issue by resnant** [optuna/optuna-dashboard#763]
# Feature Request

I noticed that the `optuna_dashboard.artifact.get_artifact_path` function lacks documentation.   
Considering it is used in the [HITL tutorial](https://optuna-dashboard.readthedocs.io/en/latest/tutorials/hitl.html), I suggest adding documentation to cover its parameters and usage examples. 
This would benefit users and enhance their experience with the Optuna Dashboard.

**Comment by c-bata** [comment]
Good catch! Thank you for your report.
