### ISSUE TITLE
Deprecation Warning in optuna-dashboard due to deprecated Optuna attribute (`study.system_attrs`)

### ISSUE THREAD

**Issue by resnant** [optuna/optuna-dashboard#765]
# Feature Request

Optuna-dashboard project currently relies on a deprecated Optuna feature`study.system_attrs`, which has been deprecated since Optuna v3.1.0.
The specific code snippet triggering the warning can be found at https://github.com/optuna/optuna-dashboard/blob/main/optuna_dashboard/preferential/samplers/gp.py#L341C39-L341C57.

While this warning may not have an immediate impact on functionality, it's worth noting that it will appear in [the preferential optimization tutorial](https://optuna-dashboard.readthedocs.io/en/latest/tutorials/preferential-optimization.html). 
As this feature and tutorial play a significant role in both Optuna and Optuna-dashboard, addressing this warning in a timely manner would be advisable to offer users a seamless experience.

**Comment by c-bata** [comment]
@resnant Thank you for your report. I opened #767 to fix this issue.
