### ISSUE TITLE
Support best trials with constraint

### ISSUE THREAD

**Issue by hrntsm** [optuna/optuna-dashboard#772]
# Feature Request

related to  https://github.com/optuna/optuna/issues/5184

The Best Trials card currently shows values that do not consider the constraints.
I would like to display the Best Trial within the feasible trials.

Checking the optuna dashboard implementation, it appears that best trial is retrieved from optuna, but for best trials(multi objective), the calculation is done at the following location in the optuna dashboard.

https://github.com/optuna/optuna-dashboard/blob/7c83aa5b3814e7ad33b596f583174ce6db0702d4/optuna_dashboard/ts/dominatedTrials.ts#L10

Is it possible to change this function  to consider the constraints?

**Comment by c-bata** [comment]
Sounds good 👍 Let me mark this issue contribution-welcome.

**Comment by hrntsm** [comment]
I received the following comments on the optuna side
https://github.com/optuna/optuna/pull/5201#issuecomment-1951714777

I think it would be a good idea to take action once the acquisition of results considering the constraints is introduced to the optuna v4 of the Study.
