### ISSUE TITLE
The results of the suggest method is not returned in preferential optimization with 2 type of variable.

### ISSUE THREAD

**Issue by hrntsm** [optuna/optuna-dashboard#796]
### Description

When performing preferential optimization, the result of the suggest method does not return when there are two types of variables: integer and float.

Is this a bug, or does it mean that the two type of variables are not supported?

### How to Reproduce

1. It is run on the basis of this [tutorial page](https://optuna-dashboard.readthedocs.io/en/latest/tutorials/preferential-optimization.html).
    - However, at the end of the following section of generator.py, I added suggest_float.
    ```py
    trial = study.ask()
    # 1. Ask new parameters
    r = trial.suggest_int("r", 0, 255)
    g = trial.suggest_int("g", 0, 255)
    b = trial.suggest_int("b", 0, 255)
    # add
    _ = trial.suggest_float("new",0,255)
    ```
2. run generate.py, it works fine for the first 4 (n_generate) trials .
3. select WORST on the dashboard and try to get the next trial on the dashboard, it does not generate a new image.
4. I started the code in debug mode and checked it, it was stuck in  `r = trial.suggest_int("r", 0, 255)`.

### Python version

3.11.0

### Optuna version

3.5.0

### optuna-dashboard version or git revision

0.14.0

### Web browser

Google Chrome

**Comment by c-bata** [comment]
Thank you for reporting! @contramundum53 Could you take a look if you have time?

**Comment by contramundum53** [comment]
I couldn't reproduce the problem.
```

from optuna_dashboard.preferential import create_study
from optuna_dashboard.preferential.samplers.gp import PreferentialGPSampler

study = create_study(
    n_generate=4,
    sampler=PreferentialGPSampler(),
    load_if_exists=True,
)

while True:
    assert study.should_generate()

    trial = study.ask()
    print(trial.number)
    # 1. Ask new parameters
    r = trial.suggest_int("r", 0, 255)
    g = trial.suggest_int("g", 0, 255)
    b = trial.suggest_int("b", 0, 255)
    _ = trial.suggest_float("x", 0, 255)  

    if len(study.trials) >= 4:
        study.report_preference(study.trials[:3], study.trials[-1])

```
This worked perfectly. Could you try this script?

**Comment by hrntsm** [comment]
To check, I changed the float to int as shown below, but this did not work either.

```py
from optuna_dashboard.preferential import create_study
from optuna_dashboard.preferential.samplers.gp import PreferentialGPSampler

study = create_study(
    n_generate=4,
    sampler=PreferentialGPSampler(),
    load_if_exists=True,
)

while True:
    assert study.should_generate()

    trial = study.ask()
    print(trial.number)
    # 1. Ask new parameters
    r = trial.suggest_int("r", 0, 255)
    g = trial.suggest_int("g", 0, 255)
    b = trial.suggest_int("b", 0, 255)
    _ = trial.suggest_int("x", 0, 255)

    if len(study.trials) >= 4:
        study.report_preference(study.trials[:3], study.trials[-1])
```

However the following(5 suggest method) worked. Sorry I am not sure what is causing the problem.

```py
    r = trial.suggest_int("r", 0, 255)
    g = trial.suggest_int("g", 0, 255)
    b = trial.suggest_int("b", 0, 255)
    _ = trial.suggest_int("x", 0, 255)
    _ = trial.suggest_int("y", 0, 255)
```

**Comment by contramundum53** [comment]
@hrntsm I found a bug in our implementation, and fixed it in #797. Could you test it?

**Comment by hrntsm** [comment]
In this case, there are four 0-255, so the result is 4228,250,625(255x255x255x255), but for some reason it was a negative value.

```py
search_space_size = np.prod([255,255,255,255]
# search_space_size is -66716671
```

**Comment by contramundum53** [comment]
Oh I see, are you using Windows?

**Comment by contramundum53** [comment]
And I think if you change the fourth parameter to `suggest_float`, would it solve your problem?

**Comment by contramundum53** [comment]
I updated the PR to use `math.prod` instead of `np.prod` so that the integer won't overflow. Does that fix your problem?

**Comment by hrntsm** [comment]
I use windows.
I tried the new PR and it works fine.
Thank you very much!
