### ISSUE TITLE
VSCode Extension doesn't show studies / Optuna Dashboard fails with `UnicodeDecodeError`

### ISSUE THREAD

**Issue by turbotimon** [optuna/optuna-dashboard#799]
### Description

I created a study as described [here](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html#new-study) but the VSCode extension doesn't show it. If i open the db with a db viewer, the study is there:

![image](https://github.com/optuna/optuna-dashboard/assets/57718207/3c558ed6-fbf1-483d-a872-6235a02c8723)

Also `optuna-dashboard example-study.db` fails with an `UnicodeDecodeError`error (meight by related?):

```bash
$ optuna-dashboard nbs/example-study.db 
/home/user/projects/venv/lib/python3.11/site-packages/optuna_dashboard/_storage_url.py:88: ExperimentalWarning: JournalStorage is experimental (supported from v3.1.0). The interface can change in the future.
  return JournalStorage(JournalFileStorage(file_path=file_path))
Traceback (most recent call last):
  File "/home/user/projects/venv/bin/optuna-dashboard", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/projects/venv/lib/python3.11/site-packages/optuna_dashboard/_cli.py", line 119, in main
    storage = get_storage(args.storage, storage_class=args.storage_class)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/venv/lib/python3.11/site-packages/optuna_dashboard/_storage_url.py", line 58, in get_storage
    return guess_storage_from_url(storage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/venv/lib/python3.11/site-packages/optuna_dashboard/_storage_url.py", line 66, in guess_storage_from_url
    return get_journal_file_storage(storage_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/venv/lib/python3.11/site-packages/optuna_dashboard/_storage_url.py", line 88, in get_journal_file_storage
    return JournalStorage(JournalFileStorage(file_path=file_path))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/venv/lib/python3.11/site-packages/optuna/_experimental.py", line 114, in wrapped_init
    _original_init(self, *args, **kwargs)
  File "/home/user/projects/venv/lib/python3.11/site-packages/optuna/storages/_journal/storage.py", line 113, in __init__
    self._sync_with_backend()
  File "/home/user/projects/venv/lib/python3.11/site-packages/optuna/storages/_journal/storage.py", line 149, in _sync_with_backend
    logs = self._backend.read_logs(self._replay_result.log_number_read)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/venv/lib/python3.11/site-packages/optuna/storages/_journal/file.py", line 184, in read_logs
    logs.append(json.loads(line))
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 99: invalid start byte
```

### How to Reproduce

1. Optuna's objective function is: According to https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html#new-study
2. Run optuna-dashboard with: Right-click on db in vscode -> Open in Optuna Dashboard
3. The extension does not show any studies
4. Starting the dashboard from cli fails with `UnicodeDecodeError`

### OS

linux / nixos 23.11 (buildFHSUserEnv)

### Python version

3.11.6 (i also tried with 3.9)

### Optuna version

3.5.0

### optuna-dashboard version or git revision

0.14.0

### Web browser

Google Chrome

**Comment by c-bata** [comment]
Thank you for your report!

For using optuna-dashboard as a Python library, you need to specify the [SQLAlchemy's database url](https://docs.sqlalchemy.org/en/20/core/engines.html) as follows:

```
$ optuna-dashboard sqlite:///nbs/example-study.db 
```

However, regarding the VS Code extension, there might be a bug. The VS Code extension internally utilizes the [browser-only version of Optuna Dashboard](https://optuna-dashboard.readthedocs.io/en/latest/getting-started.html#browser-only-version-experimental), which is also accesible at https://optuna.github.io/optuna-dashboard/.

Could you please try dragging and dropping your SQLite3 file onto https://optuna.github.io/optuna-dashboard/? Also, could you share the error traces from the Google Chrome developer console?

**Comment by turbotimon** [comment]
Hi @c-bata, thanks for your quick reply 🚀

1. `optuna-dashboard sqlite:///...`: Sorry, my bad 🥴 But i'm guessing im not the only stupid, so maybe a meaningful error message would help? Maybe this would be a *good-first-issue*?

2. *dragging and dropping your SQLite3 file onto https://optuna.github.io/optuna-dashboard/*: This works fine without an error and i can see my study. Is there another way to narrow down the problem? I tried to reinstall the extension and also tried out vscodium, but same behaviour..

**Comment by turbotimon** [comment]
**Update:** As i wake up this morning, opening the same sqlite db with the vscode extension (still v0.2.0) suddenly works. I have no idea why, probably the Browser-only version has changed?

**Comment by c-bata** [comment]
Thank you for letting me know! I'm not sure, but it might be related to #756.

**Comment by turbotimon** [comment]
Don't think so, or at least not directly related as I tried several times even after reinstalling the extension and using vscode & codium. But maybe the os restart helped. Maybe also a browser cache problem?

**Comment by keisuke-umezawa** [comment]
@turbotimon 
In that case, do we still need to merge https://github.com/optuna/optuna-dashboard/pull/800 ?

**Comment by turbotimon** [comment]
@keisuke-umezawa i would recommend. I mixed up two issues in this issue because i initially thought they were related (but aren't)

1. Vscode plugin didn't showed studies -> solved
2. cli command `optuna-dashboard example.db` fails because sqlite prefix is missing. This is not a bug but I suppose that lot of users will fall for that trap so the merge will improve user experience

**Comment by keisuke-umezawa** [comment]
@turbotimon 
ok! I will review it soon. Thank you.
