### ISSUE TITLE
Regression: Trial user attributes not being displayed on release v0.4.0

### ISSUE THREAD

**Issue by andrescodas** [optuna/optuna-dashboard#87]
# Bug reports

Trial user attributes not being displayed on release v0.4.0

## Expected Behavior

I expect to see Trial user attributes

## Current Behavior and Steps to Reproduce

I'm checking two installations of optuna-dashboard, one of version v0.3.1 and another v0.4.0.  They point to the same storage, however, the lastest dont show the expected Trial user attributes
![Screenshot from 2021-04-19 18-42-27](https://user-images.githubusercontent.com/164282/115307056-11e27f00-a13f-11eb-909c-c4f703c7d6cf.png)
![Screenshot from 2021-04-19 18-43-29](https://user-images.githubusercontent.com/164282/115307122-26267c00-a13f-11eb-9610-0cc6a4b0e286.png)

## Context

Please provide any relevant information about your setup.
This is important in case the issue is not reproducible except for under certain conditions.

working on 
```bash
$ python -c 'import optuna; print(optuna.__version__)'
2.6.0

$ optuna-dashboard --version
0.3.1
```

*NOT* working on 
```bash
$ python -c 'import optuna; print(optuna.__version__)'
2.7.0

$ optuna-dashboard --version
0.4.0
```

**Comment by c-bata** [comment]
Hi @andrescodas. Thank you for reporting this bug.
I fixed this at #88 and released https://github.com/optuna/optuna-dashboard/releases/tag/v0.4.1.

**Comment by HendrikKlug-synthara** [comment]
Hi, how can the user attributes be shown in the optuna dashboard?
They don't show up for:
optuna: `2.10.0` and optuna-dashboard: `0.5.0`

these are the visualization options that I can chose from:
![image](https://user-images.githubusercontent.com/94362637/144997030-721dc107-e4cf-4c35-90e0-251d2ae5ec83.png)

**Comment by c-bata** [comment]
@HendrikKlug-synthara You can check trial_user_attrs from the Trial table.

**Comment by HendrikKlug-synthara** [comment]
Hi @c-bata, thanks for your answer! What do you mean with the "Trial table"? 
I'm not able to see user attributes that I set with `        trial.set_user_attr('test', 'hi')
` in the table of optuna-dashboard.

**Comment by c-bata** [comment]
"Trial Table" is a table component located at the bottom of the page.

![](https://user-images.githubusercontent.com/5564044/114265667-20d57d00-9a2d-11eb-8b9c-69541c9b4a28.gif)

You can press the pull-down menu to check trial user attributes.

**Comment by HendrikKlug-synthara** [comment]
oh that's great, thanks for the demo :)
