### ISSUE TITLE
UI based unit test & functional test libraries setup

### ISSUE THREAD

**Issue by hegdeashwin** [optuna/optuna-dashboard#94]
# Feature Request

I will recommend to add Test suits/framework on UI layer for unit and functional testing during development.

As the dashboard is built using React, I will highly recommend to use the most popular test library [@testing-library/react](https://github.com/testing-library/react-testing-library)  and [jest](https://jestjs.io/docs/getting-started) to write unit tests for UI/Component layer and utility functions.

For functional tests, we could use [Cypress.io](https://www.cypress.io/).

I can start the contribution on the above work. Let me know your thoughts, I'm not sure if you guys have already planned this.

**Comment by keisuke-umezawa** [comment]
Note
For functional tests, we introduced Playwright. ref: https://github.com/optuna/optuna-dashboard/pull/484.
