### ISSUE TITLE
Fix and update Installation guide

### ISSUE THREAD

**Issue by kAIto47802** [optuna/optuna-dashboard#952]
### Description

There are several incorrect statements in the [optuna-dashbord installation guide](https://optuna-dashboard.readthedocs.io/en/stable/getting-started.html):

- In the documentation, it is stated that after cloning the optuna-dashboard GitHub repository, one should move to the `optuna` directory. However, the correct directory to move to is `optuna-dashboard`.
   <img width="541" alt="Screenshot 2024-08-30 at 16 14 20" src="https://github.com/user-attachments/assets/5e5e0f28-1f4e-4302-b370-9f99fd72e561">
- The compiling guide is outdated and inconsistent with the instructions in [CONTRIBUTING.md](https://github.com/optuna/optuna-dashboard/blob/main/CONTRIBUTING.md).
   <img width="482" alt="Screenshot 2024-08-30 at 16 22 02" src="https://github.com/user-attachments/assets/43bc4d07-5b9d-4f61-80cb-a6c111c8f44a">
- It says ``See CONTRIBUTING.md for more details,'' but the link points to the optuna repository's [CONTRIBUTING.md](https://github.com/optuna/optuna/blob/master/CONTRIBUTING.md). The correct link should be to the optuna-dashboard repository's [CONTRIBUTING.md](https://github.com/optuna/optuna-dashboard/blob/main/CONTRIBUTING.md).
   <img width="375" alt="Screenshot 2024-08-30 at 16 30 09" src="https://github.com/user-attachments/assets/089ff4e8-3e98-4874-a8f7-ab5152a1d59b">

Additionally, the optuna-dashboard repository does not have an issue template for documentation-related issues. It might be helpful to add one.

### How to Reproduce

-

### Python version

-

### Optuna version

-

### optuna-dashboard version or git revision

-

### Web browser

Google Chrome, Firefox, etc.

**Comment by c-bata** [comment]
Good catch! Thank you for reporting.

**Comment by c-bata** [comment]
Regarding the GitHub issue template, let me keep it as is. Because I would like to recommend to create pull requests rather than filing an issue.
