### ISSUE TITLE
dashboard keeps showing 'now loading'. 

### ISSUE THREAD

**Issue by unicorn343** [optuna/optuna-dashboard#957]
I used Optuna to optimize the hyperparameters of Random Forest and LightGBM, but the dashboard keeps showing 'now loading'. Can anyone tell me what's going on
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/1b636f72-2235-49e9-a883-dc587ed8354d">

**Comment by albert-92** [comment]
That's funny. 5 minutes ago I installed optuna-dashboard and the same is happening here.
It only shows 'now loading' and nothing happends.
`optuna-dashboard sqlite:///trials0001.db --host 0.0.0.0` is how I started the dashboard.

**Comment by albert-92** [comment]
Btw. here that is the same issue and there is a workaround described: https://github.com/optuna/optuna-dashboard/issues/956

**Comment by unicorn343** [comment]
> Btw. here that is the same issue and there is a workaround described: #956



> 顺便说一句，这是同样的问题，并且描述了一种解决方法：#956

thanks ,it works well
