### ISSUE TITLE
Optuna uses local browser time, not server time

### ISSUE THREAD

**Issue by jannik-el** [optuna/optuna-dashboard#971]
### Description

When running runs in optuna, you can track the trial running time in the dashboard. This dashboard plots the time axis however in the local browser running time, and not in the server running time. (Very small issue do not prioritise, but you can probably also fix it within one line of code maybe??) 

![image](https://github.com/user-attachments/assets/c7fd4079-ec8c-4706-8b3e-1c67842273b5)
The second trial has actually only been running a few seconds, yet it is already "running" for 2 hours because the server it is running on is in UTC and I am in CEST. 

### How to Reproduce

Is explained above, relates purely to the location of optuna-dashboard server, and client browser. 

### Python version

3.10.10

### Optuna version

3.6.1

### optuna-dashboard version or git revision

0.15.1

### Web browser

Brave, Chrome, Edge

**Comment by c-bata** [comment]
Thank you for your report. It was fixed at #906 and was released at [v0.16.0](https://github.com/optuna/optuna-dashboard/releases/tag/v0.16.0).

**Comment by jannik-el** [comment]
Ah cheers, didn't see that issue when looking through closed related issues, hope others can use mine as a stepping stone to that one - in short for those who have not immediately understood what the fix is, use a newer version of optuna-dashboard to fix.
