### ISSUE TITLE
Slice plot does not support boolean parameter values

### ISSUE THREAD

**Issue by cartisan** [optuna/optuna-dashboard#977]
### Description

**Observed behavior:**
When I select a categorical parameter that contains boolean values in the slice plot (first plot shown in the analytics page) then both values on the x-axis are represented as `[Object object]`.
![image](https://github.com/user-attachments/assets/c410ded7-b4d6-4736-a86d-26c3f1b5b800)

**Expected behavior:**
The plot shows the actual values, `True` and `False` on the x-axis.

**Observations:**
This seems a problem with optuna-dashbord and not optuna, when I create a slice plot in optuna (code below) I see the values represented correctly in the plotly graph.
![image](https://github.com/user-attachments/assets/4971f06f-c577-4f49-95af-1912359cb33c)

I'm not familiar with React, but the problem seems to be [here](https://github.com/optuna/optuna-dashboard/blob/81fa76b3de2bbb63ba8b658fac9067e724a0712e/tslib/react/src/components/PlotSlice.tsx#L225):
```
  const feasibleValues = feasibleTrials.map(
    (t) => selectedParamTarget.getTargetValue(t) as number
  )
```
where the code assumes the values of the x-axis are numbers, which is not the case for boolean hyperspace parameters. I would guess that this also breaks for string values of categorical parameters.

**Code to reproduce optuna plot**
```
import optuna
from plotly.io import show
def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_categorical("y", [True, False])
    if y:
        return x**2
    else:
        return x*2
sampler = optuna.samplers.TPESampler(seed=10)
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=10)
fig = optuna.visualization.plot_slice(study, params=["x", "y"])
show(fig)
```

### How to Reproduce

1. Optuna's objective function is not relevant here, but search space needs to contain a categorical parameter that contains boolean values.
2. Run optuna-dashboard.
3. Open analytics page, then select a boolean parameter in the slice plot.
4. An error occurs.

### Python version

3.11

### Optuna version

3.6.1

### optuna-dashboard version or git revision

0.16.2

### Web browser

Google Chrome

**Comment by wassname** [comment]
I also have this problem.


```
  const feasibleValues = feasibleTrials.map(
    (t) => selectedParamTarget.getTargetValue(t) as number
  )
```

I think this is just typechecking not type coersion. Usually "[Object object]" happens when you try to display an unsupported type as a string. So it must be somewhere else

**Comment by wassname** [comment]
Ah I think [I found it](https://github.com/wassname/optuna-dashboard/commits/main/). It seems that the way categorical as stored has changed.

So 
```js
 (c) => c?.toString() ?? "null"
```
to
```js
 (c) => c?.value?.toString() ?? "null"
```
everywhere it occurs

**Comment by Spider-netizen** [comment]
@wassname Thanks for this.
Can you tell what the last working version would be?

**Comment by wassname** [comment]
I'm not sure sorry, I've only recently starting using it, so I don't know if it was ever working. But that's normal, it's a active volunteer project.
