### ISSUE TITLE
Add x-axis labels to categorical slice plot

### ISSUE THREAD

**Issue by brethvoice** [optuna/optuna-dashboard#98]
# Feature Request

For categorical hyper-parameters, Tensorboard works pretty well because a person can see what the choices are on the x-axis.  Please make the slice plot behave in a similar way, at least by labeling the x-axis for the categorical choices.

It currently looks like this:
![Slice_no_x_axis_label](https://user-images.githubusercontent.com/11823408/118870610-be399180-b8b4-11eb-9dae-308f93f39069.JPG)

As you can see, there is no label on the x-axis so the choices of the categorical hyper-parameter pertaining to each column must be guessed/inferred another way.

**Comment by sdrobert** [comment]
I think this might be a browser/plotly version issue. Here are screenshots of a categorical slice of the same data using four different browsers:

Brave 1.25.70
![brave](https://user-images.githubusercontent.com/7460683/121056558-50360b00-c78c-11eb-91a7-9a8e9ff5707a.png)

Chrome 91.0.4472.77
![chrome](https://user-images.githubusercontent.com/7460683/121056689-765bab00-c78c-11eb-8ff8-c8ea8d8f55fb.png)

Firefox 88.0
![firefox](https://user-images.githubusercontent.com/7460683/121056705-7a87c880-c78c-11eb-8131-1fb14d23836b.png)

Edge 91.0.864.41
![edge](https://user-images.githubusercontent.com/7460683/121056724-7fe51300-c78c-11eb-81e6-214ce8f96d3f.png)

Not sure if this an optuna-dashboard issue or a plotly issue or a dash issue or what. Regardless, as you can see above, you _can_ find a browser that shows those labels.

Best,
Sean

**Comment by brethvoice** [comment]
@sdrobert I am using the exact same Chrome version (91.0.4472.77) as you.  Here are versions of Pyhon libraries I am using; please let me know how they compare with yours:

optuna 2.7.0
optuna-dashboard 0.4.1
plotly 4.14.3

**Comment by sdrobert** [comment]
The versions of the three libraries in my environment are the same as yours. Here's a dump of my conda environment:

```
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alembic                   1.6.2              pyhd8ed1ab_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bottle                    0.12.18                    py_0    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py39hf3d152e_0    conda-forge
cliff                     3.7.0              pyhd8ed1ab_1    conda-forge
cmaes                     0.8.2              pyh44b312d_0    conda-forge
cmd2                      1.5.0            py39hf3d152e_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorlog                  5.0.1            py39hf3d152e_0    conda-forge
greenlet                  1.1.0            py39he80948d_0    conda-forge
importlib-metadata        4.0.1            py39hf3d152e_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_0    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
mako                      1.1.4              pyh44b312d_0    conda-forge
markupsafe                2.0.0            py39h3811e60_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.20.2           py39hdbf815f_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
optuna                    2.7.0              pyhd8ed1ab_0    conda-forge
optuna-dashboard          0.4.1              pyhd8ed1ab_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pbr                       5.6.0              pyhd8ed1ab_0    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
prettytable               2.1.0              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyperclip                 1.8.1              pyhd3deb0d_0    conda-forge
python                    3.9.4           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pyyaml                    5.4.1            py39h3811e60_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
scikit-learn              0.24.2           py39h4dfa638_0    conda-forge
scipy                     1.6.3            py39hee8e79c_0    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlalchemy                1.4.15           py39h3811e60_0    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
stevedore                 3.3.0            py39hf3d152e_1    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

I'm on Windows, by the by. Maybe try with a fresh install of Firefox, just in case?

**Comment by brethvoice** [comment]
[env.txt](https://github.com/optuna/optuna-dashboard/files/6611008/env.txt)
I have a few differences (see attached0.  Could you upload a file of your environment which I could use to replicate it?

**Comment by brethvoice** [comment]
@sdrobert I am using Windows as well, so this should [work](https://datascience.stackexchange.com/a/38127/93564) to export according to Data Science Stack Exchange:

`conda list --export > package-list.txt`

**Comment by sdrobert** [comment]
Here's a printout (github doesn't like yaml) depending on your OS. Tested both (though only viewed from Windows browser.

<details>
<summary>Linux</summary>
<p>

``` yaml
name: optuna-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alembic=1.6.2=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bottle=0.12.18=py_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py39hf3d152e_0
  - cliff=3.7.0=pyhd8ed1ab_1
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=1.5.0=py39hf3d152e_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=5.0.1=py39hf3d152e_0
  - greenlet=1.1.0=py39he80948d_0
  - importlib-metadata=4.0.1=py39hf3d152e_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libgomp=9.3.0=h2828fa1_19
  - liblapack=3.9.0=9_openblas
  - libopenblas=0.3.15=pthreads_h8fe5266_0
  - libstdcxx-ng=9.3.0=h6de172a_19
  - mako=1.1.4=pyh44b312d_0
  - markupsafe=2.0.0=py39h3811e60_0
  - ncurses=6.2=h58526e2_4
  - numpy=1.20.2=py39hdbf815f_0
  - openssl=1.1.1k=h7f98852_0
  - optuna=2.7.0=pyhd8ed1ab_0
  - optuna-dashboard=0.4.1=pyhd8ed1ab_0
  - packaging=20.9=pyh44b312d_0
  - pbr=5.6.0=pyhd8ed1ab_0
  - pip=21.1.1=pyhd8ed1ab_0
  - plotly=4.14.3=pyh44b312d_0
  - prettytable=2.1.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyperclip=1.8.1=pyhd3deb0d_0
  - python=3.9.4=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python_abi=3.9=1_cp39
  - pyyaml=5.4.1=py39h3811e60_0
  - readline=8.1=h46c0cb4_0
  - retrying=1.3.3=py_2
  - scikit-learn=0.24.2=py39h4dfa638_0
  - scipy=1.6.3=py39hee8e79c_0
  - setuptools=49.6.0=py39hf3d152e_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.15=py39h3811e60_0
  - sqlite=3.35.5=h74cdb3f_0
  - stevedore=3.3.0=py39hf3d152e_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h21135ba_1
  - tqdm=4.60.0=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - tzdata=2021a=he74cb21_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
```
</p></details>

<details>
<summary>Windows</windows>
<p>

``` yaml
name: D:\conda-envs\optuna-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.6.5=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bottle=0.12.18=py_0
  - brotlipy=0.7.0=py38h294d835_1001
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py38haa244fe_0
  - cffi=1.14.5=py38hd8c33c5_0
  - cliff=3.8.0=pyhd8ed1ab_0
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=2.0.1=py38haa244fe_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=5.0.1=py38haa244fe_0
  - cryptography=3.4.7=py38hd7da0ea_0
  - greenlet=1.1.0=py38h885f38d_0
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.5.0=py38haa244fe_0
  - intel-openmp=2021.2.0=h57928b3_616
  - joblib=1.0.1=pyhd8ed1ab_0
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - liblapack=3.9.0=9_mkl
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.1.4=pyh44b312d_0
  - markupsafe=2.0.1=py38h294d835_0
  - mkl=2021.2.0=hb70f87d_389
  - msys2-conda-epoch=20160418=1
  - numpy=1.20.3=py38h09042cb_0
  - openssl=1.1.1k=h8ffe710_0
  - optuna=2.8.0=pyhd8ed1ab_0
  - packaging=20.9=pyh44b312d_0
  - pbr=5.6.0=pyhd8ed1ab_0
  - pip=21.1.2=pyhd8ed1ab_0
  - prettytable=2.1.0=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyee=7.0.4=pyh9f0ad1d_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pyppeteer=0.2.2=py_1
  - pyreadline3=3.3=py38haa244fe_1
  - pysocks=1.7.1=py38haa244fe_3
  - python=3.8.10=h7840368_1_cpython
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python_abi=3.8=1_cp38
  - pyyaml=5.4.1=py38h294d835_0
  - scikit-learn=0.24.2=py38h5d5d464_0
  - scipy=1.6.3=py38he847743_0
  - setuptools=52.0.0=py38haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.17=py38h294d835_0
  - sqlite=3.35.5=h8ffe710_0
  - stevedore=3.3.0=py38haa244fe_1
  - tbb=2021.2.0=h2d74725_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tqdm=4.61.0=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - websockets=8.1=py38h294d835_3
  - wheel=0.36.2=pyhd3deb0d_0
  - win_inet_pton=1.1.0=py38haa244fe_2
  - wincertstore=0.2=py38haa244fe_1006
  - yaml=0.2.5=he774522_0
  - zipp=3.4.1=pyhd8ed1ab_0
```
</p>
</details>

In general I avoid mixing PyPI and conda whenever possible.

**Comment by brethvoice** [comment]
> Here's a printout (github doesn't like yaml) depending on your OS.
> 
> Linux
> Windows
> Tested both (though only viewed from Windows browser. In general I avoid mixing PyPI and conda whenever possible.
> 
> EDIT: These are for cloning my environment. To create, save to env.yaml, then
> 
> ```shell
> conda env create -f env.yaml
> ```

I noticed your Windows .yml file did not have Optuna Dashboard, so I [installed](https://anaconda.org/conda-forge/optuna-dashboard) it via conda-forge after installing everything else from there according to your file.  Unfortunately, I still do not get the x-axis labels.  Here are the contents of my exported .yml file; want to try using it @sdrobert to see if you can replicate the issue?

channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.6.5=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bottle=0.12.18=py_0
  - brotlipy=0.7.0=py38h294d835_1001
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py38haa244fe_0
  - cffi=1.14.5=py38hd8c33c5_0
  - cliff=3.8.0=pyhd8ed1ab_0
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=2.0.1=py38haa244fe_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=5.0.1=py38haa244fe_0
  - cryptography=3.4.7=py38hd7da0ea_0
  - greenlet=1.1.0=py38h885f38d_0
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.5.0=py38haa244fe_0
  - intel-openmp=2021.2.0=h57928b3_616
  - joblib=1.0.1=pyhd8ed1ab_0
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - liblapack=3.9.0=9_mkl
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.1.4=pyh44b312d_0
  - markupsafe=2.0.1=py38h294d835_0
  - mkl=2021.2.0=hb70f87d_389
  - msys2-conda-epoch=20160418=1
  - numpy=1.20.3=py38h09042cb_0
  - openssl=1.1.1k=h8ffe710_0
  - optuna=2.8.0=pyhd8ed1ab_0
  - optuna-dashboard=0.4.1=pyhd8ed1ab_0
  - packaging=20.9=pyh44b312d_0
  - pbr=5.6.0=pyhd8ed1ab_0
  - pip=21.1.2=pyhd8ed1ab_0
  - prettytable=2.1.0=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyee=7.0.4=pyh9f0ad1d_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pyppeteer=0.2.2=py_1
  - pyreadline3=3.3=py38haa244fe_1
  - pysocks=1.7.1=py38haa244fe_3
  - python=3.8.10=h7840368_1_cpython
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python_abi=3.8=1_cp38
  - pyyaml=5.4.1=py38h294d835_0
  - scikit-learn=0.24.2=py38h5d5d464_0
  - scipy=1.6.3=py38he847743_0
  - setuptools=52.0.0=py38haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.17=py38h294d835_0
  - sqlite=3.35.5=h8ffe710_0
  - stevedore=3.3.0=py38haa244fe_1
  - tbb=2021.2.0=h2d74725_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tqdm=4.61.0=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - websockets=8.1=py38h294d835_3
  - wheel=0.36.2=pyhd3deb0d_0
  - win_inet_pton=1.1.0=py38haa244fe_2
  - wincertstore=0.2=py38haa244fe_1006
  - yaml=0.2.5=he774522_0
  - zipp=3.4.1=pyhd8ed1ab_0

**Comment by sdrobert** [comment]
My apologies. I will test that environment.

Would you please reformat it into a verbatim block?

**Comment by brethvoice** [comment]
> My apologies. I will test that environment.
> 
> Would you please reformat it into a verbatim block?

I think I reformatted the reply above.  Here it is again just in case:

```
name: optuna-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alembic=1.6.2=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bottle=0.12.18=py_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py39hf3d152e_0
  - cliff=3.7.0=pyhd8ed1ab_1
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=1.5.0=py39hf3d152e_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=5.0.1=py39hf3d152e_0
  - greenlet=1.1.0=py39he80948d_0
  - importlib-metadata=4.0.1=py39hf3d152e_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libgomp=9.3.0=h2828fa1_19
  - liblapack=3.9.0=9_openblas
  - libopenblas=0.3.15=pthreads_h8fe5266_0
  - libstdcxx-ng=9.3.0=h6de172a_19
  - mako=1.1.4=pyh44b312d_0
  - markupsafe=2.0.0=py39h3811e60_0
  - ncurses=6.2=h58526e2_4
  - numpy=1.20.2=py39hdbf815f_0
  - openssl=1.1.1k=h7f98852_0
  - optuna=2.7.0=pyhd8ed1ab_0
  - optuna-dashboard=0.4.1=pyhd8ed1ab_0
  - packaging=20.9=pyh44b312d_0
  - pbr=5.6.0=pyhd8ed1ab_0
  - pip=21.1.1=pyhd8ed1ab_0
  - plotly=4.14.3=pyh44b312d_0
  - prettytable=2.1.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyperclip=1.8.1=pyhd3deb0d_0
  - python=3.9.4=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python_abi=3.9=1_cp39
  - pyyaml=5.4.1=py39h3811e60_0
  - readline=8.1=h46c0cb4_0
  - retrying=1.3.3=py_2
  - scikit-learn=0.24.2=py39h4dfa638_0
  - scipy=1.6.3=py39hee8e79c_0
  - setuptools=49.6.0=py39hf3d152e_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.15=py39h3811e60_0
  - sqlite=3.35.5=h74cdb3f_0
  - stevedore=3.3.0=py39hf3d152e_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h21135ba_1
  - tqdm=4.60.0=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - tzdata=2021a=he74cb21_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010

```

**Comment by brethvoice** [comment]
@sdrobert I accidentally was pasting in stuff that was what you sent me instead, so if you are getting the email notification I apologize...you will need to come to Github and copy directly from here.

**Comment by sdrobert** [comment]
Ok, I've double-checked with the environment that you sent me and I can still see the categories on chrome. Sorry @brethvoice, I dunno.

**Comment by brethvoice** [comment]
> Ok, I've double-checked with the environment that you sent me and I can still see the categories on chrome. Sorry @brethvoice, I dunno.

Well it looks like this is a non-issue so I will close.  Thanks for verifying that it cannot be replicated @sdrobert.

**Comment by brethvoice** [comment]
> The versions of the three libraries in my environment are the same as yours. Here's a dump of my conda environment:
> 
> ```
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                 conda_forge    conda-forge
> _openmp_mutex             4.5                       1_gnu    conda-forge
> alembic                   1.6.2              pyhd8ed1ab_0    conda-forge
> attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
> backports                 1.0                        py_2    conda-forge
> backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
> bottle                    0.12.18                    py_0    conda-forge
> ca-certificates           2021.5.30            ha878542_0    conda-forge
> certifi                   2021.5.30        py39hf3d152e_0    conda-forge
> cliff                     3.7.0              pyhd8ed1ab_1    conda-forge
> cmaes                     0.8.2              pyh44b312d_0    conda-forge
> cmd2                      1.5.0            py39hf3d152e_0    conda-forge
> colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
> colorlog                  5.0.1            py39hf3d152e_0    conda-forge
> greenlet                  1.1.0            py39he80948d_0    conda-forge
> importlib-metadata        4.0.1            py39hf3d152e_0    conda-forge
> joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
> ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
> libblas                   3.9.0                9_openblas    conda-forge
> libcblas                  3.9.0                9_openblas    conda-forge
> libffi                    3.3                  h58526e2_2    conda-forge
> libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
> libgfortran-ng            9.3.0               hff62375_19    conda-forge
> libgfortran5              9.3.0               hff62375_19    conda-forge
> libgomp                   9.3.0               h2828fa1_19    conda-forge
> liblapack                 3.9.0                9_openblas    conda-forge
> libopenblas               0.3.15          pthreads_h8fe5266_0    conda-forge
> libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
> mako                      1.1.4              pyh44b312d_0    conda-forge
> markupsafe                2.0.0            py39h3811e60_0    conda-forge
> ncurses                   6.2                  h58526e2_4    conda-forge
> numpy                     1.20.2           py39hdbf815f_0    conda-forge
> openssl                   1.1.1k               h7f98852_0    conda-forge
> optuna                    2.7.0              pyhd8ed1ab_0    conda-forge
> optuna-dashboard          0.4.1              pyhd8ed1ab_0    conda-forge
> packaging                 20.9               pyh44b312d_0    conda-forge
> pbr                       5.6.0              pyhd8ed1ab_0    conda-forge
> pip                       21.1.1             pyhd8ed1ab_0    conda-forge
> plotly                    4.14.3             pyh44b312d_0    conda-forge
> prettytable               2.1.0              pyhd8ed1ab_0    conda-forge
> pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
> pyperclip                 1.8.1              pyhd3deb0d_0    conda-forge
> python                    3.9.4           hffdb5ce_0_cpython    conda-forge
> python-dateutil           2.8.1                      py_0    conda-forge
> python-editor             1.0.4                      py_0    conda-forge
> python_abi                3.9                      1_cp39    conda-forge
> pyyaml                    5.4.1            py39h3811e60_0    conda-forge
> readline                  8.1                  h46c0cb4_0    conda-forge
> retrying                  1.3.3                      py_2    conda-forge
> scikit-learn              0.24.2           py39h4dfa638_0    conda-forge
> scipy                     1.6.3            py39hee8e79c_0    conda-forge
> setuptools                49.6.0           py39hf3d152e_3    conda-forge
> six                       1.16.0             pyh6c4a22f_0    conda-forge
> sqlalchemy                1.4.15           py39h3811e60_0    conda-forge
> sqlite                    3.35.5               h74cdb3f_0    conda-forge
> stevedore                 3.3.0            py39hf3d152e_1    conda-forge
> threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
> tk                        8.6.10               h21135ba_1    conda-forge
> tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
> typing-extensions         3.7.4.3                       0    conda-forge
> typing_extensions         3.7.4.3                    py_0    conda-forge
> tzdata                    2021a                he74cb21_0    conda-forge
> wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
> wheel                     0.36.2             pyhd3deb0d_0    conda-forge
> xz                        5.2.5                h516909a_1    conda-forge
> yaml                      0.2.5                h516909a_0    conda-forge
> zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
> zlib                      1.2.11            h516909a_1010    conda-forge
> ```
> 
> I'm on Windows, by the by. Maybe try with a fresh install of Firefox, just in case?

@sdrobert just FYI, neither of us had plotly as part of the environment, but apparently that is not a requirement.  You did have it in your original list, but not in the .yml export for some reason.

**Comment by sdrobert** [comment]
> @sdrobert just FYI, neither of us had plotly as part of the environment, but apparently that is not a requirement. You did have it in your original list, but not in the .yml export for some reason.

My primary browser is Brave, so I'd initially messed around with plotly trying to solve this problem. I even forked the repo to start A PR (which is why the windows list didn't initially have optuna-dashboard - it was installed in dev mode). optuna-dashboard uses the node.js version of plotly, not the python plotly.
